config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # get 'home/index'
  
  root to: "projects#index"

  resources :projects do
    member do
      post :add_comment
      patch :change_status
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord

  after_create_commit do
    broadcast_append_to "project_#{project_id}_activity",
                        target: "activity-list",
                        partial: "projects/activity",
                        locals: { activity: self }
  end

  belongs_to :project
  belongs_to :user

  validates :activity_type, presence: true, inclusion: { in: ['comment', 'status_change'] }
  validates :content, presence: true, if: -> { activity_type == 'comment' }
  validates :status_change, presence: true, if: -> { activity_type == 'status_change' }

  default_scope { order(created_at: :asc) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  before_validation :initiate_status, if: :new_record?

  has_many :activities, dependent: :destroy

  validates :name, presence: true
  validates :status, presence: true

  def initiate_status
    self.status = 'Not Started'
  end

  # change the status of the project
  def change_status(user, new_status)
    old_status = status
    update(status: new_status)

    activities.create(
      user: user,
      activity_type: 'status_change',
      status_change: "#{old_status} to #{new_status}"
    )
  end

  # add a comment to the project
  def add_comment(user, content)
    activities.create(
      user: user,
      activity_type: 'comment',
      content: content
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :activities

  def fullname
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy, :add_comment, :change_status]

  def index
    # @projects = Project.all
    @projects = Project.page(params[:page]).per(10)

    respond_to do |format|
      format.html # Default - renders index.html.erb
      format.json { render json: @projects }
    end
  end

  def show
    @activities = @project.activities.includes(:user)
    @activity = Activity.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def edit
    # @project is already set by the before_action
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed.'
  end

  def add_comment
    if @project.add_comment(current_user, params[:content])
      @activity = @project.activities.last
  
      respond_to do |format|
        format.html { redirect_to @project }
        format.turbo_stream
      end
    else
      render json: { errors: @activity.errors.full_messages }, status: :unprocessable_entity
    end
    # redirect_to @project, notice: 'Comment was successfully added.'
  end
  
  def change_status
    if @project.change_status(current_user, params[:status])
      @activity = @project.activities.last
      respond_to do |format|
        format.html { redirect_to @project }
        format.turbo_stream
      end
    else
      render json: { errors: @activity.errors.full_messages }, status: :unprocessable_entity
    end
    # redirect_to @project, notice: 'Project status was successfully updated.'
  end

  private

  # Use callbacks to share common setup or constraints between actions
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through
  def project_params
    params.require(:project).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectConversation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mt-5">
      <div class="row">
        <div class="col-md-6 offset-md-3">

          <% if notice %>
            <div class="alert alert-primary" role="alert">
              <%= notice %>
            </div>
          <% end %>

          <% if alert %>
            <div class="alert alert-danger" role="alert">
              <%= alert %>
            </div>
          <% end %>

          <%= link_to "Projects", projects_path %> | <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 offset-md-3 mt-3">
          <div class="card">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/projects/_activity.html.erb
<div class="activity-item">
    <div class="activity-meta">
    <span class="activity-user"><%= activity.user.fullname %></span>
    <span class="activity-time"><%= time_ago_in_words(activity.created_at) %> ago, at <%= activity.created_at.strftime("%b %d, %Y %H:%M") %></span>
    </div>
    
    <% if activity.activity_type == 'comment' %>
    <div class="activity-comment">
        <%= simple_format(activity.content) %>
    </div>
    <% else %>
    <div class="activity-status-change">
        Changed status: <%= activity.status_change %>
    </div>
    <% end %>
</div>

app/views/projects/_form.html.erb
<%= form_with model: project, local: true do |form| %>
    <% if project.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(project.errors.count, "error") %> prohibited this post from being saved:</h2>
            <ul>
                <% project.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="actions mt-3">
        <%= form.submit %>
    </div>
<% end %>

app/views/projects/add_comment.turbo_stream.erb
<%= turbo_stream.append "conversation-list" do %>
  <%= render partial: "projects/activity", locals: { activity: @activity } %>
<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<div class="card-header bg-primary text-white">
  <h1>Edit Projects</h1>
</div>

<div class="card-body">
  <div class="row mb-3">
      <%= link_to "Back to Project", project_path(@project) %>
  </div>

    <%= render 'form', project: @project %>
</div>

app/views/projects/index.html.erb
<div class="card-header bg-primary text-white">
    <h1>Projects</h1>
</div>

<div class="card-body">
    <%= link_to "New", new_project_path %>

    <table class="table mt-3">
        <thead>
            <tr>
            <th scope="col">Name</th>
            <th scope="col">Status</th>
            <th scope="col">-</th>
            </tr>
        </thead>
        <tbody>
            <% if @projects.any? %>
                <% @projects.each do |project| %>
                    <tr>
                        <td><%= project.name %></td>
                        <td><%= project.status %></td>
                        <td><%= link_to "Details", project_path(project)%></td>
                    </tr>
                <% end %>
            <% else %>
                <tr>
                    <td>No projects.</td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= paginate @projects %>
</div>

app/views/projects/new.html.erb
<div class="card-header bg-primary text-white">
    <h4>New Project</h4>
</div>

<div class="card-body">
    <div class="row mb-3">
        <%= link_to "Back to Projects", projects_path %>
    </div>

    <%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<div class="card-header bg-primary text-white">
  <h1>Projects</h1>
</div>

<div class="card-body">
      <%= link_to "New", new_project_path %> | <%= link_to "Edit", edit_project_path(@project) %>

  <div class="project-details mt-3">
    <h1><%= @project.name %></h1>
    <p><%= @project.description %></p>
    
    <div class="project-status">
      <strong>Status:</strong> <%= @project.status %>
      
      <% if current_user %> <!-- Only show if user is logged in -->
        <%= form_with url: change_status_project_path(@project), method: :patch, class: 'status-form' do |form| %>
          <%= form.select :status, ['Not Started', 'In Progress', 'On Hold', 'Completed'], { selected: @project.status } %>
          <%= form.submit "Update Status" %>
        <% end %>
      <% end %>
    </div>
    
    <h2>Activity History</h2>
    <%= turbo_stream_from "project_#{@project.id}_activity" %>
    <div class="activity-list" id="activity-list">
      <hr>
      <%= render partial: "activity", collection: @activities %>
    </div>
    
    <hr>
    <% if current_user %> <!-- Only show if user is logged in -->
      <%= turbo_frame_tag "new_comment" do %>
        <div class="add-comment">
          <h3>Add Comment</h3>
          <%= form_with url: add_comment_project_path(@project), method: :post, local: false do |form| %>
            <div class="field">
              <%= form.text_area :content, rows: 4, placeholder: 'Write your comment here...' %>
            </div>
            
            <div class="actions">
              <%= form.submit "Post Comment" %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>